// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVM3hhmOqFe963o01aU3AvU__tGX3q5mA',
    appId: '1:76252632003:web:70878148ce4f5f5627e376',
    messagingSenderId: '76252632003',
    projectId: 'evently-app-435de',
    authDomain: 'evently-app-435de.firebaseapp.com',
    storageBucket: 'evently-app-435de.firebasestorage.app',
    measurementId: 'G-LF4QNK6M90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoFLZDMtlwFnqbRLUMN_ADVWykers6Fhs',
    appId: '1:76252632003:android:63a0d4e51a0f20e727e376',
    messagingSenderId: '76252632003',
    projectId: 'evently-app-435de',
    storageBucket: 'evently-app-435de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWegDDGqy_Ob_B0ufnHahXiodLV3AicbE',
    appId: '1:76252632003:ios:8ca5b4f9205c990527e376',
    messagingSenderId: '76252632003',
    projectId: 'evently-app-435de',
    storageBucket: 'evently-app-435de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWegDDGqy_Ob_B0ufnHahXiodLV3AicbE',
    appId: '1:76252632003:ios:8ca5b4f9205c990527e376',
    messagingSenderId: '76252632003',
    projectId: 'evently-app-435de',
    storageBucket: 'evently-app-435de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVM3hhmOqFe963o01aU3AvU__tGX3q5mA',
    appId: '1:76252632003:web:2c1ea050cde2676e27e376',
    messagingSenderId: '76252632003',
    projectId: 'evently-app-435de',
    authDomain: 'evently-app-435de.firebaseapp.com',
    storageBucket: 'evently-app-435de.firebasestorage.app',
    measurementId: 'G-Y2DK09J9GJ',
  );
}
